name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "ğŸ This job's status is ${{ job.status }}."

  build:
    runs-on: ubuntu-latest
#    needs: Explore-GitHub-Actions
    steps:
      - run: echo "Code build"

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test lint"

  unitest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test unitest"

  configure-secrets:
    environment: first
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve secrets
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
          env_var: ${{ vars.VAR_FROM_ENV }}
        run: |
           echo "$super_secret"

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, unitest, configure-secrets]
    steps:
      - run: echo "Deploy"
